"""add user_accounts

Revision ID: 7bb1e35ae1d0
Revises: d152e8de3793
Create Date: 2026-05-30 11:53:03.205237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb1e35ae1d0'
down_revision: Union[str, None] = 'd152e8de3793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_accounts_slack_user_id'), 'user_accounts', ['slack_user_id'], unique=False)
    op.create_index(op.f('ix_user_accounts_tenant_id'), 'user_accounts', ['tenant_id'], unique=False)
    op.create_index('uq_user_account_slackuser', 'user_accounts', ['tenant_id', 'slack_user_id'], unique=True)
    op.create_index('uq_user_account_username', 'user_accounts', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_account_username', table_name='user_accounts')
    op.drop_index('uq_user_account_slackuser', table_name='user_accounts')
    op.drop_index(op.f('ix_user_accounts_tenant_id'), table_name='user_accounts')
    op.drop_index(op.f('ix_user_accounts_slack_user_id'), table_name='user_accounts')
    op.drop_table('user_accounts')
    # ### end Alembic commands ###