"""add access_control_enabled to tenants

Revision ID: d152e8de3793
Revises: 948197cb7865
Create Date: 2026-05-29 17:42:34.000382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd152e8de3793'
down_revision: Union[str, None] = '948197cb7865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('access_control_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'access_control_enabled')
    # ### end Alembic commands ###