"""add is_admin to slack_users

Revision ID: ee2ccc59a564
Revises: a022d7586713
Create Date: 2026-05-20 14:26:39.289446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2ccc59a564'
down_revision: Union[str, None] = 'a022d7586713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_slack_users_email'), 'slack_users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_users_email'), table_name='slack_users')
    op.drop_column('slack_users', 'is_admin')
    # ### end Alembic commands ###